# Generated by Django 5.1.5 on 2025-06-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Is the product generally available (can be overridden by variant availability)?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image or default for variants.', null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as a featured product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for the product. Variants can override this.', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='e.g., S, M, L, XL, 200g, 1kg', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='e.g., Red, Blue, Green, Onyx Black', max_length=50, null=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit for this specific variant.', max_length=100, null=True, unique=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text="Override product's base price for this variant. If blank, base price is used.", max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available units for this specific variant.')),
                ('image', models.ImageField(blank=True, help_text='Image specific to this variant.', null=True, upload_to='products/variants/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this variant currently available/active?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['product', 'size', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
