# Generated by Django 5.1.5 on 2025-06-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_stock_alter_product_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for the image (for SEO and accessibility).', max_length=255, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Set as a featured image in the gallery (optional).')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Additional Product Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
