# Generated by Django 5.1.5 on 2025-06-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
