# Generated by Django 5.1.5 on 2025-06-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Internal title for this banner (e.g., 'Men's Summer Sale').", max_length=200)),
                ('image', models.ImageField(help_text='Banner image (e.g., 1200x400 pixels).', upload_to='slideshow_banners/%Y/%m/')),
                ('caption_title', models.CharField(blank=True, help_text='Title text to display on the banner.', max_length=100, null=True)),
                ('caption_text', models.CharField(blank=True, help_text='Short descriptive text on the banner.', max_length=255, null=True)),
                ('link_url', models.URLField(blank=True, help_text='Full URL this banner should link to (e.g., a promotion page).', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display in the slideshow (0 first).')),
                ('is_active', models.BooleanField(default=True, help_text='Is this banner currently active and should be displayed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_on_category_page', models.ForeignKey(blank=True, help_text='Select a parent category page where this banner should appear. Leave blank for banners shown elsewhere (not used by current logic).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_banners', to='store.category')),
            ],
            options={
                'verbose_name': 'Slideshow Banner',
                'verbose_name_plural': 'Slideshow Banners',
                'ordering': ['display_on_category_page', 'display_order', '-created_at'],
            },
        ),
    ]
