# Generated by Django 5.1.5 on 2025-06-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_slideshowbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshowbanner',
            options={'ordering': ['display_on_homepage', 'display_on_category_page', 'display_order', '-created_at'], 'verbose_name': 'Slideshow Banner', 'verbose_name_plural': 'Slideshow Banners'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as a best-selling product.'),
        ),
        migrations.AddField(
            model_name='slideshowbanner',
            name='display_on_homepage',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this banner on the homepage slideshow.'),
        ),
        migrations.AlterField(
            model_name='slideshowbanner',
            name='display_on_category_page',
            field=models.ForeignKey(blank=True, help_text='Select a parent category page where this banner should appear.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorypage_banners', to='store.category'),
        ),
    ]
