# Generated by Django 5.1.5 on 2025-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_slideshowbanner_options_product_is_bestseller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The announcement message. Emojis are supported. Keep it concise for the strip.')),
                ('link_url', models.URLField(blank=True, help_text='Optional: URL to link the announcement to.', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Check this to make the announcement visible on the site.')),
                ('start_date', models.DateTimeField(blank=True, help_text='When this announcement should start appearing (optional).', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When this announcement should stop appearing (optional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Announcement',
                'verbose_name_plural': 'Site Announcements',
                'ordering': ['-updated_at'],
            },
        ),
    ]
