# Generated by Django 5.1.5 on 2025-06-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide a URL to an external image.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide a URL to an external image for this variant.', max_length=1024, null=True),
        ),
    ]
