# Generated by Django 5.1.5 on 2025-06-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_image_url_productvariant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image_url',
        ),
    ]
