# Generated by Django 5.1.5 on 2025-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Enter a URL to an image for your profile picture.', max_length=500, null=True),
        ),
    ]
